### ISSUE TITLE
Navigation 

### ISSUE THREAD

**Issue by Marianna-Ikonomou** [Marianna-Ikonomou/Capstone---Find-my-Pet#2]
## Value Proposition

**As a User and owner of a lost Pet I want to reach people so that I can find it** 

## Description
![Capstone App-Idea](https://user-images.githubusercontent.com/122877765/225333860-37148fda-2d96-40f3-936e-ff68365f2368.png)

## Acceptance Criteria

- [ ] The first page should display the name of the App and two buttons.
- [ ] One Button goes to the Lost Page and the other to the Found/Located Page.
      ​

## Tasks

- [ ] Add Header
- [ ] Add two Buttons on first Page
- [ ] Each Button should go to a different Page
      ​

## Complexity

M-L
