### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Marianna-Ikonomou** [Marianna-Ikonomou/Capstone---Find-my-Pet#3]
## Value Proposition
As a User and owner of a lost Pet I want to reach people so that I can find it
​

## Description
<img width="349" alt="Screenshot 2023-03-17 at 12 32 37" src="https://user-images.githubusercontent.com/122877765/225893570-29f0b6ec-d7eb-47e5-a8e9-f0e79fdc3894.png">

## Acceptance Criteria

- [ ] The Home Page should display the name of the App.
- [ ] Under the App name are two buttons.
- [ ] under the two buttons is a map.
- [ ] under the map is a third button.

## Tasks

- [ ] Create a Header that sticks in place.
- [ ] Create three buttons.
- [ ] Fetch and display a map.  
      ​

## Complexity
M

**Comment by lenzloesche** [comment]
under acceptance you could write: the button reads "Lost", etc. because these become your tests.
under tasks you need to be more detailed.
where do you get a map from?

**Comment by Marianna-Ikonomou** [comment]
Good point! Thank you. 👍
