### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by Marianna-Ikonomou** [Marianna-Ikonomou/Capstone---Find-my-Pet#4]
## Value Proposition
As a User and owner of a lost Pet I want people to reach me.
​

## Description

<img width="358" alt="Screenshot 2023-03-17 at 12 38 57" src="https://user-images.githubusercontent.com/122877765/225894615-1a1de25f-72cf-418e-8538-43f82a49cdd4.png">

## Acceptance Criteria

- [ ] This page should have a Form where the user can put information and upload a photo or small video about the lost pet.
- [ ] The user should be able to put there contact info.
- [ ] The user should be able to download the form and a QR-Code.  
      ​

## Tasks

- [ ] Create a form with four inputs and a Button.
- [ ] First input is for uploading images and videos.
- [ ] Second input is for information (When, Where,... ) about pet.
- [ ] Third input is for contact info of user.
- [ ] Fourth input is for inserting users email for downloading Ad.
- [ ] Create on the bottom a button for posting the Ad.
      ​
