### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by Marianna-Ikonomou** [Marianna-Ikonomou/Capstone---Find-my-Pet#5]
As a user I want to see all of the info I put in the form as card or add at the front page and also be able to download it.
​

## Description
<img width="514" alt="Screenshot 2023-03-28 at 12 10 50" src="https://user-images.githubusercontent.com/122877765/228204066-473568bb-baac-49b1-a32d-0d9a3d75ff8e.png">

## Acceptance Criteria

- [ ] When the form created show button for downloading it as a PDF and/or QR-Code
- [ ] Show created form at the front page.

## Tasks

- [ ] Search how to convert and download a file as a PDF and QR-code with VSCode.
- [ ] Add functioning download button under the form.
- [ ] All created forms should be visible at the front page. 
      ​

## Complexity

L?
