### ISSUE TITLE
Toggle between Lost/Located map

### ISSUE THREAD

**Issue by Marianna-Ikonomou** [Marianna-Ikonomou/Capstone---Find-my-Pet#6]
As a user I want to switch between the lost and located maps so I can see other missing adds and if someone has spotted my pet somewhere or vice versa.
​
## Description
<img width="505" alt="Screenshot 2023-03-28 at 12 54 39" src="https://user-images.githubusercontent.com/122877765/228215880-f83b3052-283b-4bca-abef-10b81d72f24b.png">

## Acceptance Criteria

- [ ] See red pins in Lost map and blue pins in Located map.
- [ ] 

## Tasks

- [ ] When Lost add is created a red pin is added to the map.
- [ ] When Located add is created a blue pin is added to the map.
- [ ] Able to switch between them.
      ​

## Complexity

L

**Comment by reyk-zepper** [comment]
all in all i know what you mean and understand what to do
maybe you can add more precise acceptance creteria and delete entrys you don"t need. i know what you mean with the tasks, little example...when i add created a red pin is added...where? with wich data?...or is it a pin on a borad, a symbolic or maybe a favourite pin...shure...everbody who has interpret it...but than it is an interpretation of an dev and we want exactly say what we want as far as we know....sometime it helps me when i think this way when i want to write a story...

but all in all it works🙌🏻

**Comment by Marianna-Ikonomou** [comment]
I see what you mean there. Thanks a lot kind Sir.
